---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Packages
    apt: name= state=latest update_cache=yes
    with_items:
      - apt-transport-https
      - openssl
      - default-jdk

- hosts: elastic
  tags: es
  become: true
  roles:
    - elastic

#- hosts: kibana
#  tags: kibana
#  become: true
#  roles:
#    - kibana

#- hosts: logstash
#  tags: logstash
#  become: true
#  roles:
#    - logstash
