---
- name: Import the Elastic Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install and add elastic apt repo
  lineinfile:
    path: /etc/apt/sources.list.d/elastic.list
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"

- name: install and add curator apt repo
  lineinfile:
    path: /etc/apt/sources.list.d/elastic.list
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "deb [arch=amd64] https://packages.elastic.co/curator/5/debian stable main"

- name: install elasticsearch
  apt:
    name:
      - elasticsearch
      - elasticsearch-curator
    state: present
    update_cache: yes

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable service elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running
  ansible.builtin.systemd:
    state: started
    name: elasticsearch
